/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2015-12-03 11:23:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.sample;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/lib/egovframework.rte.ptl.mvc-3.5.0.jar", Long.valueOf(1449059094222L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/egovframework.rte.ptl.mvc-3.5.0.jar!/META-INF/taglib.tld", Long.valueOf(1428632376000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/include/include-header.jsp", Long.valueOf(1449134710048L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1448944891835L));
    _jspx_dependants.put("/WEB-INF/include/include-body.jsp", Long.valueOf(1449049224041L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<!-- META -->\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\t<title></title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"  href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- SCRIPT -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" charset=\"utf-8\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- top -->\r\n");
      out.write("\t\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("  \t\t\t<div class=\"container-fluid\">\r\n");
      out.write("    \t\t\t<div class=\"navbar-header\">\r\n");
      out.write("      \t\t\t\t<a class=\"navbar-brand\" href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"> 홈페이지 </a><span class=\"fa fa-heart pulse2\"></span>\t\r\n");
      out.write("      \t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("      \t\t\t\t\t<span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span>\r\n");
      out.write("      \t\t\t\t</button>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t<div>\r\n");
      out.write("    \t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("      \t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("        \t\t<!-- <li class=\"active\"><a href=\"#\">Home</a></li> -->\r\n");
      out.write("        \t\t\t<li><a href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"> 게시판 </a></li>\r\n");
      out.write("\r\n");
      out.write("      \t\t\t</ul>\r\n");
      out.write("      \t\t<!-- if not login state -->\r\n");
      out.write("      \t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      \t\t<!-- if login state -->\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<!-- bottom -->\r\n");
      out.write("\t\t<div class=\"home-bottom\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- Login modal -->\r\n");
      out.write("\t\t\t<div class=\"modal-buttons\">\r\n");
      out.write("  \t\t\t\t<div class=\"modal fade\" id=\"loginModal\" role=\"dialog\">\r\n");
      out.write("    \t\t\t\t<div class=\"modal-dialog modal-sm\">\r\n");
      out.write("       \t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("        \t\t\t\t\t<div class=\"modal-header\"><button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t          \t\t\t\t<h4 class=\"modal-title\"> 로그인 </h4>\r\n");
      out.write("        \t\t\t\t\t</div>\r\n");
      out.write("      \t\t\t\t\t\r\n");
      out.write("\t\t\t        \t<!-- Login form -->\r\n");
      out.write("       \t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("       \t\t\t\t\t\t\t<form role=\"form\" id=\"loginForm\" autocomplete=\"off\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t<span> 아이디 <input type=\"text\" class=\"form-control\" name=\"id\"></span>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span> 비밀번호 <input type=\"password\" class=\"form-control\" name=\"password\"></span>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" id=\"loginSubmit\"> Login </button>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\"> Close </button>\r\n");
      out.write("  \t\t\t\t\t\t\t\t</form>\r\n");
      out.write("  \t\t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("  \t\t\t<!-- Join modal -->\r\n");
      out.write("  \t\t\t\t<div class=\"modal fade\" id=\"joinModal\" role=\"dialog\">\r\n");
      out.write("    \t\t\t\t<div class=\"modal-dialog modal-sm\">\r\n");
      out.write("       \t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("        \t\t\t\t\t<div class=\"modal-header\"><button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t          \t\t\t\t<h4 class=\"modal-title\"> 회원가입 </h4>\r\n");
      out.write("        \t\t\t\t\t</div>\r\n");
      out.write("      \t\t\t\r\n");
      out.write("\t\t\t        \t<!-- Join form -->\r\n");
      out.write("       \t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("       \t\t\t\t\t\t\t<form role=\"form\" id=\"joinForm\" autocomplete=\"off\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t<span> 아이디 <input type=\"text\" class=\"form-control\" name=\"id\" onkeyup=\"joinIdCheck(this.value)\"></span>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t<br/> <span id=\"joinIdCheck\"></span>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span> 비밀번호 <input type=\"password\" class=\"form-control\" name=\"password1\" id=\"password1\"></span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<br/>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span> 재확인 <input type=\"password\" class=\"form-control\" name=\"password2\" onkeyup=\"joinPasswordCheck(this.value)\"></span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<br/> <span id=\"passwordCheck\"></span>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t<span> 닉네임 <input type=\"text\" class=\"form-control\" name=\"name\"> </span>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t\t<br/>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" id=\"joinSubmit\"> Join </button>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\"> Close </button> <br/>\r\n");
      out.write("  \t\t\t\t\t\t\t\t</form>\r\n");
      out.write("  \t\t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\t");
      out.write("\r\n");
      out.write("<form id=\"commonForm\" name=\"commonForm\"></form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("            $(\"#loginSubmit\").on(\"click\", function(e){ // 로그인\r\n");
      out.write("            \tfor (var i=0; i<2; i++) {\r\n");
      out.write("        \t\t\tif (loginForm[i].value == null || loginForm[i].value == \"\") {\r\n");
      out.write("        \t\t\t\talert (\"빈칸이 있습니다!\");\r\n");
      out.write("        \t\t\t\tloginForm[i].focus(); \r\n");
      out.write("        \t\t\treturn false;\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\t}         \r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                fn_login();\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            $(\"#joinSubmit\").on(\"click\", function(e){ // 회원가입\r\n");
      out.write("            \tfor (var i=0; i<3; i++) {\r\n");
      out.write("        \t\t\tif (joinForm[i].value == null || joinForm[i].value == \"\") {\r\n");
      out.write("        \t\t\t\talert (\"빈칸이 있습니다!\");\r\n");
      out.write("        \t\t\t\tjoinForm[i].focus(); \r\n");
      out.write("        \t\t\treturn false;\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\t}\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                fn_join();\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            $(\"#logout\").on(\"click\", function(e){ // 로그아웃\r\n");
      out.write("            \te.preventDefault();\r\n");
      out.write("                fn_logout();\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        function fn_login() {\r\n");
      out.write("            var comSubmit = new ComSubmit(\"loginForm\");\r\n");
      out.write("            comSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("            comSubmit.submit();\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function fn_join() {\r\n");
      out.write("            var comSubmit = new ComSubmit(\"joinForm\");\r\n");
      out.write("            comSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("            comSubmit.submit();\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function fn_logout() {\r\n");
      out.write("            var comSubmit = new ComSubmit();\r\n");
      out.write("            comSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("            comSubmit.submit();\r\n");
      out.write("        }\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <form id=\"frm\" name=\"frm\" enctype=\"multipart/form-data\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <colgroup>\r\n");
      out.write("                <col width=\"15%\">\r\n");
      out.write("                <col width=\"*\"/>\r\n");
      out.write("            </colgroup>\r\n");
      out.write("            <caption>게시글 작성</caption>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th scope=\"row\">제목</th>\r\n");
      out.write("                    <td><input type=\"text\" id=\"TITLE\" name=\"TITLE\"></input></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\" >\r\n");
      out.write("                        <textarea rows=\"20\" cols=\"100\" title=\"내용\" id=\"CONTENTS\" name=\"CONTENTS\"></textarea>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div id=\"fileDiv\">\r\n");
      out.write("            <p>\r\n");
      out.write("                <input type=\"file\" id=\"file\" name=\"file_0\">\r\n");
      out.write("                <a href=\"#this\" class=\"btn\" id=\"delete\" name=\"delete\">삭제</a>\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("         \r\n");
      out.write("        <br/><br/>\r\n");
      out.write("        <a href=\"#this\" class=\"btn\" id=\"addFile\">파일 추가</a>\r\n");
      out.write("        <a href=\"#this\" class=\"btn\" id=\"write\">작성하기</a>\r\n");
      out.write("        <a href=\"#this\" class=\"btn\" id=\"list\">목록으로</a>\r\n");
      out.write("    </form>\r\n");
      out.write("     \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<form id=\"commonForm\" name=\"commonForm\"></form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var gfv_count = 1;\r\n");
      out.write("     \r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("            $(\"#list\").on(\"click\", function(e){ //목록으로 버튼\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                fn_openBoardList();\r\n");
      out.write("            });\r\n");
      out.write("             \r\n");
      out.write("            $(\"#write\").on(\"click\", function(e){ //작성하기 버튼\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                fn_insertBoard();\r\n");
      out.write("            });\r\n");
      out.write("             \r\n");
      out.write("            $(\"#addFile\").on(\"click\", function(e){ //파일 추가 버튼\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                fn_addFile();\r\n");
      out.write("            });\r\n");
      out.write("             \r\n");
      out.write("            $(\"a[name='delete']\").on(\"click\", function(e){ //삭제 버튼\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                fn_deleteFile($(this));\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("         \r\n");
      out.write("        function fn_openBoardList(){\r\n");
      out.write("            var comSubmit = new ComSubmit();\r\n");
      out.write("            comSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("            comSubmit.submit();\r\n");
      out.write("        }\r\n");
      out.write("         \r\n");
      out.write("        function fn_insertBoard(){\r\n");
      out.write("            var comSubmit = new ComSubmit(\"frm\");\r\n");
      out.write("            comSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("            comSubmit.submit();\r\n");
      out.write("        }\r\n");
      out.write("         \r\n");
      out.write("        function fn_addFile(){\r\n");
      out.write("            var str = \"<p><input type='file' name='file_\"+(gfv_count++)+\"'><a href='#this' class='btn' name='delete'>삭제</a></p>\";\r\n");
      out.write("            $(\"#fileDiv\").append(str);\r\n");
      out.write("            $(\"a[name='delete']\").on(\"click\", function(e){ //삭제 버튼\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                fn_deleteFile($(this));\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("         \r\n");
      out.write("        function fn_deleteFile(obj){\r\n");
      out.write("            obj.parent().remove();\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/include/include-header.jsp(18,48) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/css/style.css");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/include/include-header.jsp(26,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/js/common.js");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/include/include-header.jsp(34,40) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /WEB-INF/include/include-header.jsp(43,24) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/sample/openBoardList.do");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/include/include-header.jsp(47,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${null == sName}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("       \t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
        out.write("\t        \t\t\t<li><a href=\"#\" class=\"navbar-right-btn\" data-toggle=\"modal\" data-target=\"#joinModal\"><span class=\"glyphicon glyphicon-user\"></span> 회원가입 </a></li>\r\n");
        out.write("        \t\t\t\t<li><a href=\"#\" data-toggle=\"modal\" data-target=\"#loginModal\"><span class=\"glyphicon glyphicon-log-in\"></span> 로그인 </a></li>\r\n");
        out.write("      \t\t\t\t</ul>\r\n");
        out.write("      \t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/include/include-header.jsp(54,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${null != sName}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
        out.write("\t        \t\t\t<li><a href=\"#\"><span class=\"glyphicon glyphicon-user\"></span><strong>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</strong>님</a></li>\r\n");
        out.write("        \t\t\t\t<li><a href=\"#this\" id=\"logout\"><span class=\"glyphicon glyphicon-log-in\"></span> 로그아웃 </a></li>\r\n");
        out.write("      \t\t\t\t</ul>\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent(null);
    // /WEB-INF/include/include-header.jsp(170,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/common/login.do");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f5.setParent(null);
    // /WEB-INF/include/include-header.jsp(176,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f5.setValue("/common/join.do");
    int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
    if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f6.setParent(null);
    // /WEB-INF/include/include-header.jsp(182,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f6.setValue("/common/logout.do");
    int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
    if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f7.setParent(null);
    // /WEB-INF/jsp/sample/boardWrite.jsp(68,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f7.setValue("/sample/openBoardList.do");
    int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
    if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f8.setParent(null);
    // /WEB-INF/jsp/sample/boardWrite.jsp(74,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f8.setValue("/sample/insertBoard.do");
    int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
    if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
    return false;
  }
}
